baseURL = 'https://archive.linux.cn/'
languageCode = 'zh-Hans'
title = 'Linux.cn Archive'
theme = "mainroad"
uglyURLs = true
paginate = 50
[Params]
opengraph = true # Enable OpenGraph if true
schema = true # Enable Schema
readmore = true # Show "Read more" button in list if true
authorbox = true # Show authorbox at bottom of pages if true
[Params.logo]
  title = "Linux.cn Archive"
[Params.thumbnail]
  visibility = ["list", "post"] # Control thumbnail visibility
[menus]
[[menus.main]]
    name = 'Home'
    pageRef = '/'
    weight = 10
[[menus.main]]
    name = 'Tags'
    pageRef = '/tags.html'
    weight = 20